import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/resources/globals.css'
import { Navigation } from '@/components/Navigation'
import { Header } from '@/components/Header'
import { DashboardCard } from '@/components/DashboardCard'
import { SideRail } from '@/components/sideRail/SideRail'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Brianne Douglas Portfolio',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body>
				<div className="justify-self-center">
					<div className="flex min-h-full flex-row gap-16">
						<div className="max-w-xs basis-3xs">
							<SideRail />
						</div>
						<div className="max-w-4xl basis-3xl">
							<DashboardCard>
								<Navigation />
								<Header size="title" />
								{children}
							</DashboardCard>
						</div>
					</div>
				</div>
			</body>
		</html>
	)
}
