import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/resources/globals.css'
import { Navigation } from '@/components/Navigation'
import { Header } from '@/components/Header'
import { DashboardCard } from '@/components/DashboardCard'
import { SideRail } from '@/components/sideRail/SideRail'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Brianne Douglas Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-row gap-16 ">
        <div className="basis-3xs ml-24 max-w-xs ">
          <SideRail />
        </div>
        <div className="basis-3xl max-w-4xl mr-24">
          <DashboardCard>
            <Navigation />
            <Header size="title" />
            {children}
          </DashboardCard>
        </div>
      </body>
    </html>
  )
}
